import type { Word } from './types';

export const wordBank: Record<string, Word[]> = {
  uz: [
    { id: 1, text: "Men", difficulty: "easy" },
    { id: 2, text: "Sen", difficulty: "easy" },
    { id: 3, text: "U", difficulty: "easy" },
    { id: 4, text: "Biz", difficulty: "easy" },
    { id: 5, text: "Siz", difficulty: "easy" },
    { id: 6, text: "Ular", difficulty: "easy" },
    { id: 7, text: "Kitob", difficulty: "easy" },
    { id: 8, text: "Maktab", difficulty: "easy" },
    { id: 9, text: "Oila", difficulty: "easy" },
    { id: 10, text: "Do'st", difficulty: "easy" },
    { id: 11, text: "Vatan", difficulty: "easy" },
    { id: 12, text: "Quyosh", difficulty: "medium" },
    { id: 13, text: "Oy", difficulty: "easy" },
    { id: 14, text: "Yulduz", difficulty: "medium" },
    { id: 15, text: "Osmon", difficulty: "easy" },
    { id: 16, text: "Yer", difficulty: "easy" },
    { id: 17, text: "Suv", difficulty: "easy" },
    { id: 18, text: "Olov", difficulty: "easy" },
    { id: 19, text: "Shamol", difficulty: "medium" },
    { id: 20, text: "Daraxt", difficulty: "medium" },
    { id: 21, text: "Gul", difficulty: "easy" },
    { id: 22, text: "Meva", difficulty: "easy" },
    { id: 23, text: "Non", difficulty: "easy" },
    { id: 24, text: "Choy", difficulty: "easy" },
    { id: 25, text: "Shakar", difficulty: "medium" },
    { id: 26, text: "Tuz", difficulty: "easy" },
    { id: 27, text: "Go'sht", difficulty: "easy" },
    { id: 28, text: "Guruch", difficulty: "medium" },
    { id: 29, text: "Sabzavot", difficulty: "medium" },
    { id: 30, text: "Mehmondo'st", difficulty: "hard" },
    { id: 31, text: "Shovqin", difficulty: "medium" },
    { id: 32, text: "Tinchlik", difficulty: "medium" },
    { id: 33, text: "Baxt", difficulty: "easy" },
    { id: 34, text: "Sevgi", difficulty: "easy" },
    { id: 35, text: "Bilim", difficulty: "easy" },
    { id: 36, text: "Hunar", difficulty: "easy" },
    { id: 37, text: "Mehnat", difficulty: "medium" },
    { id: 38, text: "Dam", difficulty: "easy" },
    { id: 39, text: "Uy", difficulty: "easy" },
    { id: 40, text: "Ko'cha", difficulty: "easy" },
    { id: 41, text: "Shahar", difficulty: "medium" },
    { id: 42, text: "Qishloq", difficulty: "medium" },
    { id: 43, text: "Yo'l", difficulty: "easy" },
    { id: 44, text: "Mashina", difficulty: "medium" },
    { id: 45, text: "Avtobus", difficulty: "medium" },
    { id: 46, text: "Poyezd", difficulty: "medium" },
    { id: 47, text: "Samolyot", difficulty: "medium" },
    { id: 48, text: "Velosiped", difficulty: "hard" },
    { id: 49, text: "Ish", difficulty: "easy" },
    { id: 50, text: "O'yin", difficulty: "easy" },
    // ... You can continue adding more following this pattern
  ],
  en: [
    { id: 9000, text: 'Apple', difficulty: 'easy' },
    { id: 9001, text: 'Computer', difficulty: 'medium' }
  ]
};